services:
  app:
    image: its-super-app:local
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: app
    environment:
      APP_ENV: dev
      OPCACHE_VALIDATE_TIMESTAMPS: 1
    volumes:
      - ./app:/var/www/html:rw,cached

  web:
    image: its-super-web:local
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: web
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - ./app/public:/var/www/html/public:ro,delegated